/**
 * Requests
 * This API manages a simple User database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  UsersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { KonfigCustom } from "./client-custom";

export class Konfig extends KonfigCustom {
  readonly users: UsersApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.users = new UsersApi(configuration);
  }

}
