# coding: utf-8

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import konfig_client
from konfig_client.model.users_list_response import UsersListResponse
from konfig_client import configuration


class TestUsersListResponse(unittest.TestCase):
    """UsersListResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
