# coding: utf-8

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import konfig_client
from konfig_client.paths.users_user_id import put
from konfig_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestUsersUserId(ApiTestMixin, unittest.TestCase):
    """
    UsersUserId unit test stubs
        Update User
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
