# coding: utf-8

# flake8: noqa

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from konfig_client.api_client import ApiClient

# import Configuration
from konfig_client.configuration import Configuration

# import exceptions
from konfig_client.exceptions import OpenApiException
from konfig_client.exceptions import ApiAttributeError
from konfig_client.exceptions import ApiTypeError
from konfig_client.exceptions import ApiValueError
from konfig_client.exceptions import ApiKeyError
from konfig_client.exceptions import ApiException

from konfig_client.client import Konfig
