# coding: utf-8
"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from konfig_client.client_custom import ClientCustom
from konfig_client.configuration import Configuration
from konfig_client.api_client import ApiClient
from konfig_client.type_util import copy_signature
from konfig_client.apis.tags.users_api import UsersApi



class Konfig(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.users: UsersApi = UsersApi(api_client)
