# coding: utf-8

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from konfig_client.paths.users.post import Create
from konfig_client.paths.users_user_id.delete import Delete
from konfig_client.paths.users_user_id.get import Get
from konfig_client.paths.users.get import List
from konfig_client.paths.users_user_id.put import Update


class UsersApi(
    Create,
    Delete,
    Get,
    List,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
