/* tslint:disable */
/* eslint-disable */
/**
 * Requests
 * This API manages a simple User database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UsersGet422Response
 */
export interface UsersGet422Response {
    /**
     * 
     * @type {string}
     * @memberof UsersGet422Response
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet422Response
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet422Response
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet422Response
     */
    'id'?: string;
}

