/* tslint:disable */
/* eslint-disable */
/**
 * Requests
 * This API manages a simple User database
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UsersUpdateResponse
 */
export interface UsersUpdateResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersUpdateResponse
     */
    'message'?: string;
}

