# coding: utf-8

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredUsersCreateResponse(TypedDict):
    pass

class OptionalUsersCreateResponse(TypedDict, total=False):
    id: str

    message: str

class UsersCreateResponse(RequiredUsersCreateResponse, OptionalUsersCreateResponse):
    pass
