# coding: utf-8

"""
    Requests

    This API manages a simple User database

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredUsersGet422Response(TypedDict):
    pass

class OptionalUsersGet422Response(TypedDict, total=False):
    name: str

    email: str

    country: str

    id: str

class UsersGet422Response(RequiredUsersGet422Response, OptionalUsersGet422Response):
    pass
